### ISSUE TITLE
Refactoring Folder Structure.

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/indokhaadyam#12]
To rearrange the code and clean it up a bit for new commers to work better on it.
```
src
├───assets
├───components
├───containers
└───index.js
```
Individual Component & Container Structure

```
component
├───component.jsx
└───component.css
```

**Comment by yeshwanth235** [comment]
I want to contribute to this under JWOC, assign to me pls.

**Comment by Shruti025** [comment]
Can I work on this under JWOC?
