### ISSUE TITLE
Counter Effect

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/indokhaadyam#15]
## Sample Wireframe 

![wireframe](https://user-images.githubusercontent.com/46641503/149675731-061aff7a-5c8d-4862-87d2-459e248b45b7.png)

# Directions

1. Check out [this](https://atmana.org/) for your reference. [Below Our Products Section]
2.  The Text and numbers should be as defined above in the wireframe. Define them inside a JSON object so that it is easier to modify them later.
3. The effect should be mobile responsive.
4. This would be a separate standalone section (second one rather). Leave some space below the title accordingly
5.  Make sure it is mobile responsive

**Comment by 03amir** [comment]
i want to work on this issue under jwoc
