### ISSUE TITLE
Update Footer UI

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/indokhaadyam#16]
## Directions:

- [Sample Reference](https://www.tilt.bike/). We don't need any Contact Sales text as shown in the reference. Rather just two lines: the title of the project followed by "Made with 💖 in India for the foodies around the globe"
- @anushbhatia would provide the colors and the font recommendations.
- Add GitHub Microanimation and link to this repo. [Reference](https://doc2pen.smaranjitghose.com/)

**Comment by whiteHatpro** [comment]
i want to work on this issue under Jwoc

**Comment by whiteHatpro** [comment]
@smaranjitghose @anushbhatia 


![screenshot-localhost_3000-2022 02 07-22_56_37](https://user-images.githubusercontent.com/77486870/152840097-340b6a25-2e0c-4582-9299-e8ed11deb612.png)


should I make the pr now?

**Comment by anushbhatia** [comment]
Looks good from my end. @smaranjitghose reviews?

**Comment by whiteHatpro** [comment]
@anushbhatia please review the pr

**Comment by whiteHatpro** [comment]
@smaranjitghose got any reviews?

**Comment by anushbhatia** [comment]
@whiteHatpro check the comments on PR first

**Comment by whiteHatpro** [comment]
@anushbhatia got something??

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
