### ISSUE TITLE
Add Basic NavBar

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/indokhaadyam#17]
# Directions
- [Sample Reference](https://app-promotional-website.vercel.app/)
- Consult with @anushbhatia for the color and the font
- It should have Home, Categories, Contact, Blog, Team
- Make sure it is mobile responsive

**Comment by riiyaaa** [comment]
I would like to work on this issue under JWOC

**Comment by riiyaaa** [comment]
The navbar is needed for the app or the website?

**Comment by smaranjitghose** [comment]
For the website

**Comment by riiyaaa** [comment]
> For the website

okayy

**Comment by Shruti025** [comment]
Hey can I take up this issue under JWOC if it is still unresolved?

**Comment by riiyaaa** [comment]
> Hey can I take up this issue under JWOC if it is still unresolved?

I will soon be done with it, wait for one more day please :(

**Comment by Shruti025** [comment]
> I will soon be done with it, wait for one more day please :(

Oh it's alright, all the best :)

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
