### ISSUE TITLE
Create Team Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/indokhaadyam#19]
# Directions:

- Sample [Reference](https://doc2pen.smaranjitghose.com/): Project Maintainers + Clan of Contributor section
- Consult @anushbhatia for the colors and font
- The list of contributors is fetched using github
- The page should be mobile responsive
- The image,text, social handle links for @anushbhatia and me should be defined inside a JSON object so that it is easier to modify

**Comment by Aniket-508** [comment]
I want to work on this under JWoC.

**Comment by 03amir** [comment]
I want to work on this under JWoC.
