### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/indokhaadyam#2]
## Directions:

- Create a simple footer for the website. [Reference](https://doc2pen.smaranjitghose.com/)
- It should have the name of the website 
- Try to add a tagline " Made with 💖 in India for the world"
- Feel free to add any micro animation or illustration

**Comment by Abhishek-Rath** [comment]
@smaranjitghose , can I work on this?

**Comment by smaranjitghose** [comment]
Sure! Currently we are working out the final color scheme and overall design, so your work might serve as a foundation for us.

**Comment by Shruti025** [comment]
hey, can I work on this issue?

**Comment by smaranjitghose** [comment]
@Shruti025 Yes! There is a lot of room for improvement especially w.r.t the design. Looking forward to your PR

**Comment by Rikky10** [comment]
Can I work on this ?

**Comment by smaranjitghose** [comment]
Let @Shruti025 give a PR within next couple of days, after that you can take over if required

**Comment by anushbhatia** [comment]
@Rikky10 would you like to add micro animation or illustartion to the project then you can take this up?

**Comment by whiteHatpro** [comment]
I want to work in this issue under JWoC.

**Comment by smaranjitghose** [comment]
Any updates @whiteHatpro ?
