### ISSUE TITLE
Set up Routing 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/indokhaadyam#26]
To set up routing with the reactjs-router library in the home pages so that we can proper flow of all the pages
![hello](https://user-images.githubusercontent.com/46641503/149675731-061aff7a-5c8d-4862-87d2-459e248b45b7.png)
At least add these three pages by default in the routes

**Comment by Priiyaa** [comment]
Hi! I would like to work on this issue under jwoc

**Comment by Priiyaa** [comment]
The routing needs to be set for which pages?

**Comment by anushbhatia** [comment]
home
contact
features

**Comment by Priiyaa** [comment]
![routing](https://user-images.githubusercontent.com/76914418/154316806-aad351f5-dcba-4ad3-91af-5d7d2dde3487.jpg)
**Is this okay?**

**Comment by anushbhatia** [comment]
no need for /user as of now directly add /contact /features

**Comment by Priiyaa** [comment]
> no need for /user as of now directly add /contact /features

ok got it.

**Comment by Priiyaa** [comment]
![route](https://user-images.githubusercontent.com/76914418/154329342-c1052cc5-0108-4e66-919c-e1c9c69886c6.jpg)
**Should I create a PR for it now?**

**Comment by anushbhatia** [comment]
yes

**Comment by Priiyaa** [comment]
I have created a PR, please review it...

**Comment by codervivek5** [comment]
I would like to work on this issue under JWOC.....plz give me a chance for contribution
