### ISSUE TITLE
Top Categories Section [Home Page]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/indokhaadyam#3]
![wireframe](https://user-images.githubusercontent.com/46641503/149675125-7bb23552-fe9c-44a6-a21b-5d99c5a675ba.png)

- Add a "Top Categories" section below the Home Page
- It should have six cards (2X3): 
      - Mithai Masti (Indian Sweets)
      - Nashta ( Indian Breakfast)
      - Chaat and Snacks
      - Fasting Food
      - Drinks
      - Main Course
  - Each card should have an image ( add some box-shadow to the card so that it is visible separately from the background-color) and on hover effect. [Check Sample](https://codepen.io/hexagoncircle/pen/XWbWKwL). 
  - On Hover, there should be a button "Check Out" which would redirect to the particular page (to be created later. Keep # for now)

**Comment by bansalshubh** [comment]
Can i work on this issue ?

**Comment by akriti143** [comment]
Can I work on this issue?

**Comment by anushbhatia** [comment]
Any update?

**Comment by manishbajagai2** [comment]
I want to work on this issue under JWOC

**Comment by manishbajagai2** [comment]
@smaranjitghose Am sorry if I am late. Have been working on it. A little newbie to work efficiently as learning takes time.

**Comment by manishbajagai2** [comment]
@smaranjitghose Shall I put these cards in a carousal with three dots at the end or just display them in a 2 x 3 fashion. Am thinking that for now i will just display them in grid and in the next issue(if created for adding carousal), i shall work on adding theses cards in carousal. How does it sound?

This much is done :

![image](https://user-images.githubusercontent.com/62448303/152665959-d5ae32b6-5d23-4ef6-88af-9f8dcdc05d3b.png)

**Comment by smaranjitghose** [comment]
- You can simply display them in 2 X 3 grid. 
- Try to implement the hover effect suggested in the reference above
- For the categories use: the three titles mentioned in the design wireframe (in the description) + Vegetarian Vendetta + Snack Satisfaction + Beverages
- No description text is required.
- Make sure that the text and the images can be defined inside a simple JSON object for easier modification

**Comment by manishbajagai2** [comment]
@smaranjitghose 
![image](https://user-images.githubusercontent.com/62448303/152683880-b3ab127c-1794-41de-b154-f6bcfb28e1c7.png)
I should create only this page right?

**Comment by manishbajagai2** [comment]
If i put the below in six categories as card title
- Mithai Masti (Indian Sweets)
- Nashta ( Indian Breakfast)
- Chaat and Snacks
- Fasting Food
- Drinks
- Main Course
Then where should i put Vegetarian Vendetta + Snack Satisfaction + Beverages

**Comment by smaranjitghose** [comment]
My bad 😅, I forgot that I had already given 6 categories. Go ahead with those. Avoid the last three

**Comment by manishbajagai2** [comment]
ok thank you

**Comment by manishbajagai2** [comment]
Am doing so now

**Comment by 03amir** [comment]
I want to work on this issue under JWOC
