### ISSUE TITLE
Add Search Bar in Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/indokhaadyam#5]
## Directions

- Sample Wireframe 

![wireframe](https://user-images.githubusercontent.com/46641503/149675731-061aff7a-5c8d-4862-87d2-459e248b45b7.png)

- [Sample Reference](https://codepen.io/huange/pen/rbqsD)

- Please make sure that the colors are consistent with the remaining website

**Comment by akriti143** [comment]
@smaranjitghose Can I work on this??

**Comment by varunwho** [comment]
@smaranjitghose can i work on this??

**Comment by smaranjitghose** [comment]
@akriti143 Sure!
We have a default search bar already. Try to make a new one (check the reference). Consult @anushbhatia w.r.t the color scheme

**Comment by akriti143** [comment]
@smaranjitghose Okk , I'll update with the new one

**Comment by combatantash** [comment]
I want to work on this issue under JWOC

**Comment by ZaidMujahid** [comment]
I want to work on this issue under JWOC

**Comment by ZaidMujahid** [comment]
I want to work on this issue under JWOC

**Comment by ZaidMujahid** [comment]
I want to work on this issue under JWOC?

**Comment by raxvab** [comment]
I want to work on this issue under JWOC it's gonna be one of the first opportunities for me to start with open source can i get this issue assigned.

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by smaranjitghose** [comment]
@combatantash Assigned to you for 2 days. After that @raxvab can take over if there are any UI updates required.

**Comment by ZaidMujahid** [comment]
@smaranjitghose After @combatantash it will be assigned to me, right? bcoz I commented after @combatantash

**Comment by smaranjitghose** [comment]
Oh my bad. I missed your comment! Yes @ZaidMujahid you can take over

**Comment by ZaidMujahid** [comment]
Sure will work on it
I have to replace the previous search bar with the new search bar, right?

**Comment by ZaidMujahid** [comment]
Assign this to me

**Comment by ZaidMujahid** [comment]
@smaranjitghose Where am I supposed to add search bar? the website is a blank page only.

**Comment by anushbhatia** [comment]
replace the current search bar with the one in the home page.

**Comment by ZaidMujahid** [comment]
But when I'm opening index.html from the public repo it is opening just a blank page

**Comment by ZaidMujahid** [comment]
@anushbhatia and the website link attach in the github repo that link is opening another website in which a search bar and some text and footer is there
![Screenshot (128)](https://user-images.githubusercontent.com/89090882/152671180-f29e2ca8-44b5-4240-a34e-ff2665882aa7.png)
This is what I'm getting after opening it form github repo
![Screenshot (129)](https://user-images.githubusercontent.com/89090882/152671193-ca931d21-5bb9-4294-b087-58216ec93e01.png)
and this is I'm getting after opening(index.html) it form my pc

**Comment by anushbhatia** [comment]
> @anushbhatia and the website link attach in the github repo that link is opening another website in which a search bar and some text and footer is there ![Screenshot (128)](https://user-images.githubusercontent.com/89090882/152671180-f29e2ca8-44b5-4240-a34e-ff2665882aa7.png) This is what I'm getting after opening it form github repo ![Screenshot (129)](https://user-images.githubusercontent.com/89090882/152671193-ca931d21-5bb9-4294-b087-58216ec93e01.png) and this is I'm getting after opening(index.html) it form my pc

remove public/index.html from the url

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by anushbhatia** [comment]
You have been assigned to this @03amir

**Comment by 03amir** [comment]
@anushbhatia  can you  please assign me, you just mentioned me.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
