### ISSUE TITLE
Update UI of Contact Us Form with Navbar

### ISSUE THREAD

**Issue by tanya-gupta25** [smaranjitghose/indokhaadyam#64]
Will create a new contact us form with responsiveness & navbar in Contact Page.

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC

**Comment by smaranjitghose** [comment]
@tanya-gupta25 Sure, we look forward to  your changes for the Contact US form.

## Some Suggestions:
- The title of the page should be centre aligned and the text can be "Get in Touch"
- Try to use some Text Animation for the title. [Sample](https://codepen.io/cassie-codes/pen/GEaZVm)
- The contact form should be strict checks for email validity, name length more than 2 and message length more than 3 (number of words)
- Try to use some Helper text animations if you wish
- For the send button,  add a micro animation like [this](https://codepen.io/shahidshaikhs/pen/PoZqNaQ)
- Lastly, integration with formcarry

Feel free to split the work across 2-4 PRs

**Comment by shivamsoni8813** [comment]
i want to contribute in this problem solution
